name: PenguorHS
version: 0.0.1.0
github: "Penguor/PenguorHS"
license: MIT
author: "Carl Schierig"
maintainer: "example@example.com"
copyright: "2020 Carl Schierig"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Penguor/PenguorHS#readme>

dependencies:
  - base >= 4.7 && < 5
  - megaparsec
  - text
  - containers

library:
  source-dirs: src

executables:
  PenguorHS-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - megaparsec
      - text
      - PenguorHS
      - containers

tests:
  integration-tests:
    main: Spec.hs
    source-dirs: test/integration
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - PenguorHS
      - hspec
      - hspec-discover
      - megaparsec

  unit-tests:
    main: Spec.hs
    source-dirs: test/unit
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - PenguorHS
      - hspec
      - hspec-discover
      - megaparsec
